Introduce integration tests
eclipse-velocitas/devenv-github-workflows pull request #16
Opened 2023-04-13 07:47 UTC by dennismeister93

2023-04-13 10:16 UTC, MP91 requested changes

2023-04-19 07:23 UTC, MP91 requested changes
seems that the workflows need the appManifest

2023-04-19 07:23 UTC, MP91 commented on .github/workflows/ci.yml
> +              - 'src/${{ matrix.language }}-sdk/**'
please adapt the checks in the next steps accordingly

2023-04-21 08:58 UTC, dennismeister93 commented on .github/workflows/ci.yml
> +            workflowsPythonCommon:
Please change this to "workflowsLangCommon" &
'src/${{ matrix.language }}-common/**'

2023-04-21 09:34 UTC, merged