Automated test as workflow
eclipse-velocitas/devenv-github-workflows pull request #40
Opened 2023-08-30 12:00 UTC by mml5bg

Changes needed to introduce automated tests for devcontainer environment as a workflow.

2023-08-31 04:43 UTC, MP91 requested changes

2023-08-31 04:43 UTC, MP91 commented on src/python-app/workflows/check-devcontainer.yml
> +          runCmd: ./tests/automated_tests/test.sh
why did you remove the push?
```suggestion
        with:
          runCmd: ./tests/automated_tests/test.sh
          push: never
```

2023-08-31 04:43 UTC, MP91 commented on src/python-app/workflows/check-devcontainer.yml
> +    - cron: "1 1 * * 1"
isn't that to often? running this on PR should be enough

2023-08-31 08:04 UTC, doosuu requested changes

2023-08-31 08:04 UTC, doosuu commented on src/python-app/workflows/check-devcontainer.yml
> +# This file is maintained by velocitas CLI, do not modify manually. Change settings in .velocitas.json
Remove this line, it is added by the CLI when syncing.

2023-08-31 08:04 UTC, doosuu commented on src/python-app/workflows/check-devcontainer.yml
> +# Copyright (c) 2022 Robert Bosch GmbH and Microsoft Corporation
```suggestion
# Copyright (c) 2023 Robert Bosch GmbH
```

2023-08-31 08:04 UTC, doosuu commented on src/python-app/workflows/check-devcontainer.yml
> +          runCmd: ./tests/automated_tests/test.sh
Where are the scripts in this PR?
Why chose bash over Python as scripting language? I'd prefer to use Python and Pytest also for reports

2023-09-19 12:28 UTC, MP91 commented on src/common/workflows/check-devcontainer.yml
> +    - cron: "1 1 * * 1"
why do we need this schedule? what should change that is not controlled by us?

2023-09-22 04:30 UTC, MP91 requested changes

2023-09-22 04:30 UTC, MP91 commented on src/common/workflows/check-devcontainer.yml
> +    - cron: "1 1 * * 1"
please change this to run daily/nightly

2023-09-22 07:51 UTC, MP91 approved these changes
lgtm

2023-09-22 10:58 UTC, doosuu approved these changes
lgtm

2023-09-22 10:59 UTC, merged