add native binaries as artifacts
eclipse-velocitas/devenv-github-workflows pull request #54
Opened 2024-04-24 10:14 UTC by MP91

2024-04-24 12:48 UTC, dennismeister93 requested changes

2024-04-24 12:48 UTC, dennismeister93 commented on src/app/workflows/build-docker-image.yml
> +            archs_array="$archs_array $arch"
doesn't it make sense to add some echo statements to show what was found and whats going on? I would also suggest to give this step a more meaningful name

2024-04-24 12:48 UTC, dennismeister93 commented on src/app/workflows/build-docker-image.yml
> +          for arch in $(echo ${{ steps.set_args.outputs.platforms }} | tr -d "linux\/,"); do
to avoid duplication this can be done beforehand and saved into envs:
$(echo ${{ steps.set_args.outputs.platforms }} | tr -d "linux\/,")

2024-04-24 12:48 UTC, dennismeister93 commented on src/app/workflows/build-docker-image.yml
> +            skopeo copy --override-arch $arch oci-archive:${{ env.APP_NAME }}-${{inputs.platform}}.tar docker-archive:${{ env.APP_NAME }}_$arch.tar
why does this docker-archive:${{ env.APP_NAME }}_$arch.tar need to be seperated by an underscore? can't we keep consistency with naming?

2024-04-24 12:48 UTC, dennismeister93 commented on src/app/workflows/build-docker-image.yml
> +      - name: "${{ env.APP_NAME }} -- Upload app"
"Upload native binaries" ? or something instead of only "Upload app"

2024-04-24 12:48 UTC, dennismeister93 commented on src/app/workflows/build-multiarch-image.yml
> +    runs-on: ubuntu-latest
please dont use latest

2024-04-24 13:18 UTC, MP91 commented on src/app/workflows/build-docker-image.yml
> +            skopeo copy --override-arch $arch oci-archive:${{ env.APP_NAME }}-${{inputs.platform}}.tar docker-archive:${{ env.APP_NAME }}_$arch.tar
I wanted to have it separated because the one with "-" is "just" oci-compliant whereas the "_" is docker-compatible, I had some trouble with that during the implementation because docker load just works with docker images...

2024-04-24 13:18 UTC, MP91 commented on src/app/workflows/build-docker-image.yml
> +      - name: "${{ env.APP_NAME }} -- Upload app"
agreed

2024-04-24 13:18 UTC, MP91 commented on src/app/workflows/build-multiarch-image.yml
> +    runs-on: ubuntu-latest
you are right, just copy'n'pasted that...

2024-04-24 13:19 UTC, MP91 commented on src/app/workflows/build-docker-image.yml
> +            archs_array="$archs_array $arch"
I don't think so, will add the archs upfront than this is not needed at all

2024-04-24 13:22 UTC, dennismeister93 commented on src/app/workflows/build-docker-image.yml
> +            archs_array="$archs_array $arch"
i was more thinking of echo "Found binary for $arch"

2024-04-26 14:23 UTC, dennismeister93 approved these changes
lgtm

2024-04-29 04:01 UTC, merged