Give job write permission
eclipse-velocitas/devenv-github-workflows pull request #56
Opened 2024-06-11 14:37 UTC by erikbosch

Necessary step to fix/merge:

- https://github.com/eclipse-velocitas/vehicle-app-python-template/pull/246
- https://github.com/eclipse-velocitas/vehicle-app-python-template/issues/240
- https://github.com/eclipse-velocitas/vehicle-app-python-template/issues/242
- https://github.com/eclipse-velocitas/vehicle-app-cpp-template/issues/101

In short:

- When you create a fork by using the templates the GITHUB_TOKEN seems to by default only give read access
- That means the release workflow does not run successfully
- Fixed by adding write rights
- Also increased timeout as building C++ is slow!
- There does not seem to be a needed to do a similar change in https://github.com/eclipse-velocitas/devenv-github-workflows/blob/main/src/python-sdk/workflows/release.yaml Maybe we inherit read/write capabilities there.

If/When merged, the ambition is to create a v6.0.3 release to be able to update the template repos in similar way

2024-06-11 15:20 UTC, dennismeister93 requested changes

2024-06-11 15:20 UTC, dennismeister93 commented on src/python-sdk/workflows/release.yaml
> +  packages: write
Are you sure those two permissions are sufficient?
I tested it with only those 2 and it didnt work :(
As far as i know github actions sets all other permissions to "none" (?) if you explicitly set any in the yaml.

2024-06-12 06:35 UTC, erikbosch commented on src/python-sdk/workflows/release.yaml
> +  packages: write
I have done two tests, for C++ not yet finished as build takes time, but looks promising. I do not know if it may depend on how your Github account is configured. Do you have a reference to your failed workflow run (with the changes from this PR) so that i can analyze it

### Python Template

Used template to create https://github.com/erikbosch/vehicle-example-app2

First run (created a release and workflow was triggered) with no modifications resulted in error.
After changing the workflow it succeeded

https://github.com/erikbosch/vehicle-example-app2/actions/workflows/release.yml


### C++ Template

Used template to create https://github.com/erikbosch/vehicle-example-app3

Similar behavior as for Python, works after fix

https://github.com/erikbosch/vehicle-example-app3/actions/workflows/release.yml

2024-06-12 07:46 UTC, erikbosch commented on src/python-sdk/workflows/release.yaml
> +  packages: write
For me the C++ release failed as the timelimit of 1800 seconds waiting for "Merge Trivy Result" was too short if triggering a release just after pushing/merging a commit, as the C++ App build can take long time. Trying with increased time interval

2024-06-12 12:38 UTC, erikbosch commented
@dennismeister93 - PR updated now

2024-06-12 13:54 UTC, dennismeister93 approved these changes
lgtm

2024-06-13 07:30 UTC, merged