Update license check and pre-commit
eclipse-velocitas/devenv-github-workflows pull request #59
Opened 2024-06-14 09:09 UTC by erikbosch

Previously both gave warnings.

- Pre-commit as using Node.js 16
- License check as error code was presented

Fixes #58 

Now also changed so that license check is performed also on push

Changes tested (for python app) on this repo https://github.com/erikbosch/vehicle-example-app2

**Example pre-commit**

- Previous build: https://github.com/erikbosch/vehicle-example-app2/actions/runs/9464628807
- New build: https://github.com/erikbosch/vehicle-example-app2/actions/runs/9513024768

Warning only present in old build
```
Run unit tests and linters
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Example License check**

- Old run: https://github.com/erikbosch/vehicle-example-app2/actions/runs/9464326913
- New run: https://github.com/erikbosch/vehicle-example-app2/actions/runs/9513024770

Old run gave warning. In new run dash output is presented.

Old:

```
Check Software Licenses
Process completed with exit code 23.
```

New:

```
[main] INFO Querying Eclipse Foundation for license data for 79 items.
[main] INFO Found 23 items.
[main] INFO Querying ClearlyDefined for license data for 57 items.
[main] INFO Found 57 items.
[main] INFO License information could not be automatically verified for the following content:
[main] INFO 
[main] INFO git/github/actions/download-artifact/v4
[main] INFO git/github/actions/setup-java/v4
[main] INFO git/github/actions/setup-node/v4
[main] INFO git/github/actions/setup-python/v5
[main] INFO git/github/actions/upload-artifact/v4
[main] INFO git/github/aquasecurity/trivy-action/0.19.0
[main] INFO git/github/dawidd6/action-download-artifact/v3
[main] INFO git/github/docker/build-push-action/v5
[main] INFO git/github/docker/setup-buildx-action/v3
[main] INFO git/github/docker/setup-qemu-action/v3
[main] INFO git/github/fountainhead/action-wait-for-check/v1.2.0
[main] INFO git/github/mikepenz/action-junit-report/v4
[main] INFO git/github/softprops/action-gh-release/v2
[main] INFO pypi/pypi/-/coverage/7.3.2
[main] INFO pypi/pypi/-/exceptiongroup/1.1.3
[main] INFO pypi/pypi/-/grpcio/1.59.0
[main] INFO pypi/pypi/-/mypy/1.5.1
[main] INFO pypi/pypi/-/paho-mqtt/1.6.1
[main] INFO pypi/pypi/-/parameterized/0.9.0
[main] INFO pypi/pypi/-/setuptools/58.1.0
[main] INFO pypi/pypi/-/typing-extensions/4.11.0
[main] INFO pypi/pypi/-/velocitas-sdk/0.14.1
[main] INFO pypi/pypi/-/wheel/0.41.2
[main] INFO 
[main] INFO This content is either not correctly mapped by the system, or requires review.
```

Changes inspired by what exist in https://github.com/eclipse-kuksa/kuksa-actions/tree/main/check-dash. If a token is available then one could consider supporting automatic review requests as well.

2024-06-14 09:17 UTC, erikbosch commented
Here we go again, two more ideas to get rid of warnings. Tested only on Python app, but have difficulties seeing that this should give problems for cpp/sdks

2024-06-25 12:34 UTC, MP91 requested changes

2024-06-25 12:34 UTC, MP91 commented on src/common/workflows/check-licenses.yml
> +      - main
why do you think this is needed or improves something? basically this should not change anything, since the licenses should not change from opening the PR till merging it. we can't push without a PR

2024-06-25 12:34 UTC, MP91 commented on src/app/workflows/gen-desired-state.yml
> +          echo "VERSION=$VERSION" >> $GITHUB_ENV
is there a benefit in using an ENV over the Github output?

at least to me setting an env seems wrong at this place

2024-06-25 12:35 UTC, MP91 commented
We also have the VELOCITAS_PROJECT_TOKEN which should do the stuff for dash

2024-06-25 12:41 UTC, erikbosch commented on src/common/workflows/check-licenses.yml
> +      - main
We are as of today a bit inconsistent, in quite many workflows we trigger on both push and pull request, like in https://github.com/eclipse-velocitas/devenv-github-workflows/blob/main/src/python-sdk/workflows/ci.yaml

The advantage that I see by triggering on "push" is that it is easy to find the result for latest commit on main, just check actions and the last run on "main", rather than trying to find the last PR merged.

2024-06-25 12:46 UTC, erikbosch commented on src/app/workflows/gen-desired-state.yml
> +          echo "VERSION=$VERSION" >> $GITHUB_ENV
Can try with step instead

2024-06-25 12:46 UTC, MP91 commented on src/common/workflows/check-licenses.yml
> +      - main
But why do you even need the result of the workflow? You can only merge a PR if the workflow is successful and once it is, the 3rd-PARTY-NOTICE contains the latest licenses, so this is on the main branch always the latest state.

2024-06-25 12:47 UTC, MP91 commented on src/common/workflows/check-licenses.yml
> +      - main
yeah we are inconsistent because for some workflows it makes sense to run it on main again, but the check-licenses it does not makes sense IMO

2024-06-25 12:50 UTC, erikbosch commented on src/common/workflows/check-licenses.yml
> +      - main
Not a big issue, I can remove it

2024-06-25 13:52 UTC, erikbosch commented
> We also have the VELOCITAS_PROJECT_TOKEN which should do the stuff for dash

You mean to request a review, similar to how we use `secrets.ECLIPSE_GITLAB_API_TOKEN` in for example Databroker. I think that makes sense, but should we do it in this PR?

```

      - name: Dash license check
        uses: eclipse-kuksa/kuksa-actions/check-dash@4
        with:
          dashinput: ${{github.workspace}}/dash-databroker-deps
          dashtoken: ${{ secrets.ECLIPSE_GITLAB_API_TOKEN }}
```

2024-06-26 09:55 UTC, MP91 approved these changes
lgtm

2024-06-26 10:01 UTC, merged